//
//  GuidePageGeneration.swift
//  FHIRKit
//
//  Copyright (c) 2022 Bitmatic Ltd.
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

/**
 A code that indicates how the page is generated.
 
 URL: http://hl7.org/fhir/guide-page-generation
 ValueSet: http://hl7.org/fhir/ValueSet/guide-page-generation
 */
public enum GuidePageGeneration: String, FHIRKitPrimitiveType {
  /// Page is proper xhtml with no templating.  Will be brought across unchanged for standard post-processing.
  case html
  
  /// Page is markdown with templating.  Will use the template to create a file that imports the markdown file prior
  /// to post-processing.
  case markdown
  
  /// Page is xml with templating.  Will use the template to create a file that imports the source file and run the
  /// nominated XSLT transform (see parameters) if present prior to post-processing.
  case xml

  /// Page will be generated by the publication process - no source to bring across.
  case generated
}
