version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - run: swift build
      - run: swift test --enable-code-coverage  --xunit-output ./results.xml --parallel
      - run: |
          xcrun llvm-cov export \
          -format=lcov \
          -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata \
          .build/x86_64-apple-macosx/debug/FHIRKitPackageTests.xctest/Contents/MacOS/FHIRKitPackageTests \
          > .lcov.info
      - store_test_results:
          path: ./lcov.info
      - codecov/upload:
          file: /Users/distiller/project/lcov.info
workflows:
  build:
    jobs:
      - build
