version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - run: swift build
      - run: swift test --enable-code-coverage  --xunit-output ./results.xml --parallel
      - store_test_results:
          path: results.xml
      - codecov/upload:
          file: /Users/distiller/project/results.xml
workflows:
  build:
    jobs:
      - build
