version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@13.9.3

jobs:
  lint:
    docker:
      - image: ghcr.io/realm/swiftlint:latest
    resource_class: small
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run linter
          command: swiftlint --reporter html > swiftlint.html
      - store_artifacts:
          path: ~/project/swiftlint.html
  build-all:
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - run:
          name: Build and Test
          command: swift test --enable-code-coverage  --xunit-output ./results.xml --parallel
      - run: |
          xcrun llvm-cov export \
          -format=lcov \
          -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata \
          .build/x86_64-apple-macosx/debug/AsclepiusPackageTests.xctest/Contents/MacOS/AsclepiusPackageTests \
          > /Users/distiller/project/lcov.info
      - store_test_results:
          path: /Users/distiller/project/lcov.info
      - store_test_results:
          path: /Users/distiller/project/results.xml
      - coverage-reporter/send_report:
          coverage-reports: "/Users/distiller/project/lcov.info"
          project-token: $CODACY_PROJECT_TOKEN
  build-r4:
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - run:
          name: Build and Test AsclepiusCore + R4 Sequence
          command: swift test --test-product R4 --enable-code-coverage --xunit-output ./results.xml --parallel
      - run:
          name: Prepare coverage results
          command: |
            xcrun llvm-cov export \
            -format=lcov \
            -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata \
            .build/x86_64-apple-macosx/debug/AsclepiusPackageTests.xctests/Contents/MacOS/AsclepiusPackageTests \
            > /Users/distiller/project/lcov.info
      - store_test_results:
          path: /Users/distiller/project/lcov.info
      - store_test_results:
          path: /Users/distiller/project/results.xml
      - coverage-reporter/send_report:
          coverage-reports: "/Users/distiller/project/lcov.info"
          project-token: $CODACY_PROJECT_TOKEN
  build-stu3:
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - run:
          name: Build and Test AsclepiusCore + STU3 Sequence
          command: swift test --test-product STU3 --enable-code-coverage --xunit-output ./results.xml --parallel
      - run:
          name: Prepare coverage results
          command: |
            xcrun llvm-cov export \
            -format=lcov \
            -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata \
            .build/x86_64-apple-macosx/debug/AsclepiusPackageTests.xctests/Contents/MacOS/AsclepiusPackageTests \
            > /Users/distiller/project/lcov.info
      - store_test_results:
          path: /Users/distiller/project/lcov.info
      - store_test_results:
          path: /Users/distiller/project/results.xml
      - coverage-reporter/send_report:
          coverage-reports: "/Users/distiller/project/lcov.info"
          project-token: $CODACY_PROJECT_TOKEN
workflows:
  version: 2
  lint-only:
    jobs:
      - lint
  lint-and-build-all:
    jobs:
      - lint
      - build-all
  lint-and-build-r4:
    jobs:
      - lint
      - build-r4
  lint-and-build-stu3:
    jobs:
      - lint
      - build-stu3
