version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@13.9.3

jobs:
  build:
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - run:
          name: install swiftlint
          command: HOMBREW_NO_AUTO_UPDATE=1 brew install swiftlint
      - run: swiftlint
      - run:
          name: Build and Test
          command: swift test --enable-code-coverage  --xunit-output ./results.xml --parallel
      - run: |
          xcrun llvm-cov export \
          -format=lcov \
          -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata \
          .build/x86_64-apple-macosx/debug/FHIRKitPackageTests.xctest/Contents/MacOS/FHIRKitPackageTests \
          > /Users/distiller/project/lcov.info
      - store_test_results:
          path: /Users/distiller/project/lcov.info
      - coverage-reporter/send_report:
          coverage-reports: "/Users/distiller/project/lcov.info"
          project-token: $CODACY_PROJECT_TOKEN
workflows:
  build:
    jobs:
      - build
