version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@13.9.3

jobs:
  lint:
    docker:
      - image: ghcr.io/realm/swiftlint:latest
    resource_class: small
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run linter
          command: swiftlint --reporter html> swiftlint.html
      - store_artifacts:
          path: ~/project/swiftlint.html
  build:
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - run:
          name: Build and Test
          command: swift test --enable-code-coverage  --xunit-output ./results.xml --parallel
      - run: |
          xcrun llvm-cov export \
          -format=lcov \
          -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata \
          .build/x86_64-apple-macosx/debug/FHIRKitPackageTests.xctest/Contents/MacOS/FHIRKitPackageTests \
          > /Users/distiller/project/lcov.info
      - store_test_results:
          path: /Users/distiller/project/lcov.info
      - store_test_results:
          path: /Users/distiller/project/results.xml
      - coverage-reporter/send_report:
          coverage-reports: "/Users/distiller/project/lcov.info"
          project-token: $CODACY_PROJECT_TOKEN

workflows:
  version: 2
  lint-and-build:
    jobs:
      - lint
      - build
